platform: 10.11.92.33

workspace:
  base: /go
  path: src/github.com/fatedier/frp

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0

pipeline:

  client-golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.15.6-alpine
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/mod:/go/pkg/mod
    binary: awecloud-access-client
    main: cmd/frpc
    when:
      branch: dev

  client-docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12
    dockerfile: build/client.dockerfile
    repo: wod/awecloud-access-client
    version: "v0.34.3"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=amd64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  client-docker-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12-arm64
    dockerfile: build/client.dockerfile
    repo: wod/awecloud-access-client
    version: "v0.34.3-arm64"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=arm64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  client-docker-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12-ppc64le
    dockerfile: build/client.dockerfile
    repo: wod/awecloud-access-client
    version: "v0.34.3-ppc64le"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=ppc64le"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  client-docker-mips64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.11-mips64le
    dockerfile: build/client.dockerfile
    repo: wod/awecloud-access-client
    version: "v0.34.3-mips64le"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=mips64le"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  client-harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  client-harbor-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3-arm64-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3-arm64
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  client-harbor-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3-ppc64le-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3-ppc64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  client-harbor-mips64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3-mips64le-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-client:v0.34.3-mips64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  server-golang:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-go-arch:1.15.6-alpine
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/mod:/go/pkg/mod
    binary: awecloud-access-server
    main: cmd/frps
    when:
      branch: dev

  server-docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12
    dockerfile: build/server.dockerfile
    repo: wod/awecloud-access-server
    version: "v0.34.3"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=amd64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  server-docker-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12-arm64
    dockerfile: build/server.dockerfile
    repo: wod/awecloud-access-server
    version: "v0.34.3-arm64"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=arm64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  server-docker-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12-ppc64le
    dockerfile: build/server.dockerfile
    repo: wod/awecloud-access-server
    version: "v0.34.3-ppc64le"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=ppc64le"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  server-docker-mips64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    pull: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.11-mips64le
    dockerfile: build/server.dockerfile
    repo: wod/awecloud-access-server
    version: "v0.34.3-mips64le"
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=mips64le"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev

  server-harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  server-harbor-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3-arm64-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3-arm64
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  server-harbor-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3-ppc64le-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3-ppc64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  server-harbor-mips64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3-mips64le-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/awecloud-access-server:v0.34.3-mips64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master